alter table programmes_de_fidelite_clients DROP column pourcentage_du_rabais_refereur;
alter table programmes_de_fidelite_clients DROP column montant_du_rabais;
alter table programmes_de_fidelite_clients DROP column rabais_en_cascade_tous_refereurs_par_le_haut;
alter table programmes_de_fidelite_clients DROP column valeur_de_la_condition_beneficiaire;
