alter table programmes_de_fidelite_clients ADD column `pourcentage_du_rabais_refereur` int(2) AFTER pourcentage_du_rabais;
alter table programmes_de_fidelite_clients ADD column `rabais_en_cascade_tous_refereurs_par_le_haut` boolean AFTER pourcentage_du_rabais_refereur;
