default: yeroth-erp-3.0-inventory-stock-recommended-hardware.pdf

yeroth-erp-3.0-inventory-stock-recommended-hardware.pdf: clean yeroth-erp-3.0-inventory-stock-recommended-hardware.tex 
	pdflatex yeroth-erp-3.0-inventory-stock-recommended-hardware
	pdflatex yeroth-erp-3.0-inventory-stock-recommended-hardware
	evince yeroth-erp-3.0-inventory-stock-recommended-hardware.pdf&

clean:
	rm -f *~ *.glo *.aux *.bbl *.brf *.idx *.bak *.ilg *.ind *.lof \
	   *.lot *.out *.thm *.toc
