default: yeroth-erp-3-0-installation-guide-standalone.pdf

yeroth-erp-3-0-installation-guide-standalone.pdf: clean yeroth-erp-3-0-installation-guide-standalone.tex 
	pdflatex yeroth-erp-3-0-installation-guide-standalone
	pdflatex yeroth-erp-3-0-installation-guide-standalone
	evince yeroth-erp-3-0-installation-guide-standalone.pdf&

clean:
	rm -f *~ *.glo *.aux *.bbl *.brf *.idx *.bak *.ilg *.ind *.lof *.log \
	   *.lot *.out *.thm *.toc
