default: yeroth-erp-3-0-software-system-uses.pdf

yeroth-erp-3-0-software-system-uses.pdf: clean yeroth-erp-3-0-software-system-uses.tex 
	pdflatex yeroth-erp-3-0-software-system-uses
	pdflatex yeroth-erp-3-0-software-system-uses
	evince yeroth-erp-3-0-software-system-uses.pdf&

clean:
	rm -f *~ *.glo *.aux *.bbl *.brf *.idx *.bak *.ilg *.ind *.lof \
	   *.lot *.out *.thm *.toc
