default: yeroth-erp-3-0-guide-dinstallation-standalone.pdf

yeroth-erp-3-0-guide-dinstallation-standalone.pdf: clean yeroth-erp-3-0-guide-dinstallation-standalone.tex 
	pdflatex yeroth-erp-3-0-guide-dinstallation-standalone
	pdflatex yeroth-erp-3-0-guide-dinstallation-standalone
	evince yeroth-erp-3-0-guide-dinstallation-standalone.pdf&

clean:
	rm -f *~ *.glo *.aux *.bbl *.brf *.idx *.bak *.ilg *.ind *.lof \
	   *.lot *.out *.thm *.toc
