/*
 * yeroth-erp-3-0-definition-user-role.hpp
 *
 *      Author: Xavier NOUMBISSI NOUNDOU, Dipl.-Inf., Ph.D. (ABD)
 */

# ifndef _YEROTH_ERP_3_0_DEFINITION_USER_ROLE_HPP_
# define _YEROTH_ERP_3_0_DEFINITION_USER_ROLE_HPP_

# define ROLE_ENGLISH_UI_NAME_YEROTH_ERP_3_0_SELLER					"Seller"
# define ROLE_ENGLISH_UI_NAME_YEROTH_ERP_3_0_STORE_KEEPER		"StoreKeeper"
# define ROLE_ENGLISH_UI_NAME_YEROTH_ERP_3_0_MANAGER				"Manager"
# define ROLE_ENGLISH_UI_NAME_YEROTH_ERP_3_0_ADMINISTRATOR	"Administrator"
# define ROLE_ENGLISH_UI_NAME_YEROTH_ERP_3_0_INVENTORY_STOCK_MANAGER	"InventoryStockManager"
# define ROLE_ENGLISH_UI_NAME_YEROTH_ERP_3_0_CASHIER				"Cashier"
# define ROLE_ENGLISH_UI_NAME_YEROTH_ERP_3_0_UNDEFINED			"Undefined"

# define ROLE_FRANCAIS_UI_NAME_YEROTH_ERP_3_0_VENDEUR				"Vendeur"
# define ROLE_FRANCAIS_UI_NAME_YEROTH_ERP_3_0_MAGASINIER		"Magasinier"
# define ROLE_FRANCAIS_UI_NAME_YEROTH_ERP_3_0_MANAGER				"Manager"
# define ROLE_FRANCAIS_UI_NAME_YEROTH_ERP_3_0_ADMINISTRATEUR		"Administrateur"
# define ROLE_FRANCAIS_UI_NAME_YEROTH_ERP_3_0_GESTIONAIRE_DES_STOCKS	"GestionaireDesStocks"
# define ROLE_FRANCAIS_UI_NAME_YEROTH_ERP_3_0_CAISSIER			"Caissier"
# define ROLE_FRANCAIS_UI_NAME_YEROTH_ERP_3_0_INDEFINI			"Indéfini"

# define ROLE_YEROTH_ERP_3_0_VENDEUR					"RoleVendeur"
# define ROLE_YEROTH_ERP_3_0_MAGASINIER				"RoleMagasinier"
# define ROLE_YEROTH_ERP_3_0_MANAGER					"RoleManager"
# define ROLE_YEROTH_ERP_3_0_ADMINISTRATEUR		"RoleAdministrateur"
# define ROLE_YEROTH_ERP_3_0_GESTIONAIRE_DES_STOCKS		"RoleGestionaireDesStocks"
# define ROLE_YEROTH_ERP_3_0_CAISSIER					"RoleCaissier"

# endif //_YEROTH_ERP_3_0_DEFINITION_USER_ROLE_HPP_
