default: yeroth-erp-3-0-PDV-materiel-informatique-recommande.pdf

yeroth-erp-3-0-PDV-materiel-informatique-recommande.pdf: clean yeroth-erp-3-0-PDV-materiel-informatique-recommande.tex 
	pdflatex yeroth-erp-3-0-PDV-materiel-informatique-recommande
	pdflatex yeroth-erp-3-0-PDV-materiel-informatique-recommande
	evince yeroth-erp-3-0-PDV-materiel-informatique-recommande.pdf&

clean:
	rm -f *~ *.glo *.aux *.bbl *.brf *.idx *.bak *.ilg *.ind *.lof \
	   *.lot *.out *.thm *.toc
