default: yeroth-erp-3-0-PDV-materiel-informatique-recommende.pdf

yeroth-erp-3-0-PDV-materiel-informatique-recommende.pdf: clean yeroth-erp-3-0-PDV-materiel-informatique-recommende.tex 
	pdflatex yeroth-erp-3-0-PDV-materiel-informatique-recommende
	pdflatex yeroth-erp-3-0-PDV-materiel-informatique-recommende
	evince yeroth-erp-3-0-PDV-materiel-informatique-recommende.pdf&

clean:
	rm -f *~ *.glo *.aux *.bbl *.brf *.idx *.bak *.ilg *.ind *.lof \
	   *.lot *.out *.thm *.toc
